service: pet-finder
frameworkVersion: '4.2.5'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-dotenv-plugin
  